module.exports = [
  {
    label: "Homepage",
    url: "http://localhost:8080",
    referenceUrl: "",
    delay: 500,
    misMatchThreshold: 0.01,
    requireSameDimensions: true,
  },
  {
    label: "Stress test of site features",
    url: "http://localhost:8080/Stress-test-of-site-features",
    referenceUrl: "",
    delay: 500,
    misMatchThreshold: 0.01,
    requireSameDimensions: true,
  },
  {
    label: "Shard theory",
    url: "http://localhost:8080/Essays/The-shard-theory-of-human-values",
    referenceUrl: "",
    delay: 500,
    misMatchThreshold: 0.01,
    requireSameDimensions: true,
  },
  {
    label: "Searching for stress-test",
    url: "http://localhost:8080/",
    referenceUrl: "",
    delay: 500,
    misMatchThreshold: 0.01,
    onReadyScript: "puppet/searchOnReady.cjs",
    requireSameDimensions: true,
  },
]
